---
name: Get latest release version

on:
  schedule:
    - cron: "* */12 * * *"

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch folding-at-home release version
        run: |
          curl -sL https://formulae.brew.sh/api/cask/folding-at-home.json | \
          jq -r ".version" > build/.version
          cat build/.version

      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Stefan Crain'
          git config --global user.email 'stefancrain@users.noreply.github.com'
          git commit --all --signoff --message="Adding new release version $(cat build/.version)" || exit 0
          git tag --annotate $(cat build/.version) --message="Automatic bump to $(cat build/.version)"

      - name: Push changes + tags
        uses: ad-m/github-push-action@master
        with:
          tags: true
          github_token: ${{ secrets.PAT }}
